Repository 777PolarFox777/Intellectus, pull requests merged in 2019-11, with the labels that each got.

#68 Add Jest for Unit-testing
  client/.babelrc
  client/.eslintrc.json
  client/jest/setupEnzyme.js
  client/package-lock.json
  client/package.json
  client/src/components/Footer/Footer.test.js
  client/src/components/Footer/index.tsx
  client/src/components/Header/Header.test.js
  client/src/components/Header/index.tsx
  client/src/components/Loader/Loader.test.js
  client/src/components/Stepper/Stepper.test.js
  client/src/components/Stepper/index.tsx
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/utils/session.js
  server/src/utils/session.test.js
Labels: testing

#69 Add Rematch instead of React-Saga
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/Header/index.tsx
  client/src/components/IntroView.tsx
  client/src/components/Loader/actions.ts
  client/src/components/Loader/initialState.ts
  client/src/components/Loader/model.ts
  client/src/components/Loader/reducer.ts
  client/src/components/Modal/actions.ts
  client/src/components/Modal/index.ts
  client/src/components/Modal/index.tsx
  client/src/components/Modal/initialState.ts
  client/src/components/Modal/model.ts
  client/src/components/Modal/reducers.ts
  client/src/components/OptionTable.tsx
  client/src/components/ProblemTable.tsx
  client/src/components/ReportModal.tsx
  client/src/components/TestResult.tsx
  client/src/components/TestView/index.tsx
  client/src/components/WatchResults.tsx
  client/src/pages/Main/actions.ts
  client/src/pages/Main/index.tsx
  client/src/pages/Main/initialState.ts
  client/src/pages/Main/model.ts
  client/src/pages/Main/reducer.ts
  client/src/pages/Main/sagas.ts
  client/src/pages/Statistics/actions.ts
  client/src/pages/Statistics/index.tsx
  client/src/pages/Statistics/initialState.ts
  client/src/pages/Statistics/model.ts
  client/src/pages/Statistics/reducer.ts
  client/src/pages/Statistics/sagas.ts
  client/src/store/actions.ts
  client/src/store/index.ts
  client/src/store/models.ts
  client/src/store/rootReducer.ts
  client/src/store/rootSaga.ts
  server/public/bundle.js
  server/public/bundle.js.gz
  server/public/index.html.gz
  server/public/styles.css
Labels: feature, frontend

#70 Fix header size in Mozilla Firefox
  client/scss/_Header.scss
  client/src/components/Header/index.tsx
Labels: bugfix, frontend

#71 INT-49 Adaptive design for main page
  client/package-lock.json
  client/public/images/share.svg
  client/public/index.html
  client/scss/_Footer.scss
  client/scss/_Header.scss
  client/scss/_Loader.scss
  client/scss/_MainPage.scss
  client/scss/_Orientation.scss
  client/scss/_variables.scss
  client/scss/main.scss
  client/src/App.tsx
  client/src/MainLayout.tsx
  client/src/components/Header/index.tsx
  client/src/components/IntroView.tsx
  client/src/pages/ContactUs.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Statistics/index.tsx
  server/public/bundle.js.gz
  server/public/images/share.svg.gz
  server/public/index.html.gz
  server/public/styles.css.gz
Labels: feature, frontend

#74 INT-36 Add last 5 problem types
  server/src/problems/constants.js
  server/src/problems/problem-template.js
  server/src/problems/problem-types/bitwise-problem.js
  server/src/problems/problem-types/change-by-mask-problem.js
  server/src/problems/problem-types/difference-problem.js
  server/src/problems/problem-types/direction-problem.js
  server/src/problems/problem-types/fragment-problem.js
  server/src/problems/problem-types/half-magic-square-problem.js
  server/src/problems/problem-types/missing-element-problem.js
  server/src/problems/problem-types/sudoku-problem.js
  server/src/problems/problem-types/sum-problem.js
  server/src/problems/problem-types/transformation-problem.js
  server/src/problems/problem-types/two-figures-easy-problem.js
  server/src/problems/problem-types/two-figures-medium-problem.js
  server/src/problems/svg-creator.js
  server/src/problems/test-creator.js
  server/src/utils/arrayGenerators.js
  server/src/utils/seedRandom.js
Labels: backend, feature

#73 Feature/int 65
  client/package-lock.json
  client/scss/_Header.scss
  client/scss/_MainPage.scss
  client/scss/_Stepper.scss
  client/scss/_TestView.scss
  client/scss/_variables.scss
  client/src/components/Header/index.tsx
  client/src/components/OptionTable.tsx
  client/src/components/ProblemTable.tsx
  client/src/components/Stepper/index.tsx
  client/src/components/TestView/index.tsx
  client/src/components/WatchResults.tsx
  client/src/pages/About.tsx
  server/package-lock.json
Labels: feature, frontend

#75 INT-46 Add share feature
  client/public/images/facebook.svg
  client/public/images/twitter.svg
  client/public/images/vk.svg
  client/public/index.html
  client/scss/_MainPage.scss
  client/src/components/IntroView.tsx
  server/public/bundle.js.gz
  server/public/images/facebook.svg.gz
  server/public/images/share.svg.gz
  server/public/images/twitter.svg.gz
  server/public/images/vk.svg.gz
  server/public/index.html.gz
  server/public/styles.css.gz
Labels: feature, frontend

#76 INT-47 Add share results feature
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/scss/_MainPage.scss
  client/scss/_Orientation.scss
  client/src/App.tsx
  client/src/components/IntroView.tsx
  client/src/components/TestResult.tsx
  client/src/index.tsx
  client/tsconfig.json
  server/public/bundle.js.gz
  server/public/index.html.gz
  server/public/styles.css.gz
Labels: feature, frontend

#81 INT-66 Result adaptive
  client/scss/_StatisticChart.scss
  client/scss/_TestResult.scss
  client/src/components/TestResult.tsx
Labels: feature, frontend

#83 INT-68 feedback form adaptive
  client/scss/_ContactUs.scss
  client/src/components/IntroView.tsx
  client/src/components/TestResult.tsx
  client/src/components/forms/ContactUsForm.tsx
Labels: feature, frontend

#87 INT-67 Add keyboard support
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/scss/_reset.scss
  client/src/components/IntroView.tsx
  client/src/components/Modal/index.tsx
  client/src/components/OptionTable.tsx
  client/src/components/ReportModal.tsx
  client/src/components/Stepper/index.tsx
  client/src/components/TestView/index.tsx
  client/src/pages/Main/handlers.ts
  client/src/pages/Main/index.tsx
  client/src/pages/Statistics/index.tsx
  client/tsconfig.json
  server/package.json
  server/public/bundle.js.gz
  server/public/styles.css.gz
Labels: feature, frontend
