Repository 777PolarFox777/Intellectus, pull requests merged in 2019-10, with the labels that each got.

#50 Feature/INT-44
  server/src/routes/feedback.js
  server/src/routes/reports.js
  server/src/utils/mailSender.js
Labels: backend

#52 Add codeoweners
  CODEOWNERS
Labels: miscellaneous

#53 Update client in server
  server/public/bundle.js
  server/public/style.css
Labels: miscellaneous

#54 Add analyze build script, store gzipped static files in server
  client/package-lock.json
  client/package.json
  client/src/components/Stepper.tsx
  client/src/components/TestView/index.tsx
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.analyze.config.js
  server/package-lock.json
  server/package.json
  server/public/bundle.js
  server/public/bundle.js.gz
  server/public/images/arrow.svg
  server/public/images/arrow.svg.gz
  server/public/images/check.svg
  server/public/images/check.svg.gz
  server/public/images/cross.svg
  server/public/images/cross.svg.gz
  server/public/images/favicon32.png
  server/public/images/favicon32.png.gz
  server/public/images/loader.svg
  server/public/images/loader.svg.gz
  server/public/images/logo.png
  server/public/images/logo.png.gz
  server/public/images/plane.svg
  server/public/images/plane.svg.gz
  server/public/images/play.svg
  server/public/images/play.svg.gz
  server/public/images/share.svg
  server/public/images/share.svg.gz
  server/public/index.html
  server/public/index.html.gz
  server/public/styles.css
  server/public/styles.css.gz
  server/src/index.js
Labels: miscellaneous

#55 Update CODEOWNERS
  CODEOWNERS
Labels: miscellaneous

#56 INT-61 Update selected problem cell view
  client/package.json
  client/scss/_TestView.scss
  client/src/components/OptionTable.tsx
  client/src/components/ProblemTable.tsx
  client/src/components/TestView/index.tsx
  client/src/pages/Main/actions.ts
  client/src/pages/Main/initialState.ts
  client/src/pages/Main/reducers.ts
  client/src/pages/Main/sagas.ts
  client/webpack.prod.config.js
  server/public/bundle.js.gz
  server/public/styles.css.gz
Labels: feature, frontend

#57 INT-45 Watch results
  client/package-lock.json
  client/scss/_Stepper.scss
  client/scss/_TestView.scss
  client/src/commonTypes.ts
  client/src/components/OptionTable.tsx
  client/src/components/ProblemTable.tsx
  client/src/components/Stepper.tsx
  client/src/components/TestResult.tsx
  client/src/components/TestView/index.tsx
  client/src/components/WatchResults.tsx
  client/src/constants.ts
  client/src/pages/Main/actions.ts
  client/src/pages/Main/index.tsx
  client/src/pages/Main/initialState.ts
  client/src/pages/Main/reducers.ts
  server/package-lock.json
  server/public/bundle.js
  server/public/bundle.js.gz
  server/public/styles.css
Labels: feature, frontend

#58 INT-53 Add statistics page
  client/.eslintrc.json
  client/scss/_Statistics.scss
  client/scss/main.scss
  client/src/components/Graph.tsx
  client/src/components/index.ts
  client/src/constants.ts
  client/src/pages/Statistics.tsx
  client/webpack.dev.config.js
Labels: feature, frontend

#63 INT-34 & INT-35 Added sudoku and magic square problems
  server/src/problems/constants.js
  server/src/problems/problem-types/bitwise-problem.js
  server/src/problems/problem-types/half-magic-square-problem.js
  server/src/problems/problem-types/missing-element-problem.js
  server/src/problems/problem-types/sudoku-problem.js
  server/src/problems/problem-types/sum-problem.js
  server/src/problems/problem-types/two-figures-easy-problem.js
  server/src/problems/problem-types/two-figures-medium-problem.js
  server/src/problems/svg-creator.js
  server/src/problems/test-creator.js
Labels: backend, feature

#60 INT-57 Report modal
  client/scss/_ContactUs.scss
  client/scss/_Modal.scss
  client/scss/_TestView.scss
  client/scss/main.scss
  client/src/commonTypes.ts
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/actions.ts
  client/src/components/Modal/index.ts
  client/src/components/Modal/initialState.ts
  client/src/components/Modal/reducers.ts
  client/src/components/ProblemTable.tsx
  client/src/components/ReportModal.tsx
  client/src/components/WatchResults.tsx
  client/src/components/forms/ContactUsForm.tsx
  client/src/components/forms/ReportForm.tsx
  client/src/components/index.ts
  client/src/pages/ContactUs.tsx
  client/src/pages/Main/index.tsx
  client/src/store/index.ts
  client/src/store/rootReducer.ts
  client/webpack.dev.config.js
  server/package-lock.json
Labels: feature, frontend

#65 Improve some problems generation
  server/public/bundle.js.gz
  server/public/index.html.gz
  server/public/styles.css.gz
  server/src/problems/problem-types/half-magic-square-problem.js
  server/src/problems/problem-types/sum-problem.js
  server/src/problems/svg-creator.js
Labels: backend, feature

#64 Update TypeScript, add schema validation for all routes, fix statistics route naming
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/MainLayout.tsx
  client/src/components/Header.tsx
  client/src/components/Loader/index.ts
  client/src/components/Loader/index.tsx
  client/src/components/Loader/reducer.ts
  client/src/components/Loader/sagas.ts
  client/src/components/OptionTable.tsx
  client/src/components/ReportModal.tsx
  client/src/components/Stepper.tsx
  client/src/components/TestResult.tsx
  client/src/components/TestView/index.tsx
  client/src/components/WatchResults.tsx
  client/src/constants.ts
  client/src/pages/ContactUs.tsx
  client/src/pages/Main/actions.ts
  client/src/pages/Main/index.tsx
  client/src/pages/Main/reducer.ts
  client/src/pages/Main/sagas.ts
  client/src/pages/Statistics.tsx
  client/src/pages/Statistics/actions.ts
  client/src/pages/Statistics/constants.ts
  client/src/pages/Statistics/index.tsx
  client/src/pages/Statistics/initialState.ts
  client/src/pages/Statistics/reducer.ts
  client/src/pages/Statistics/sagas.ts
  client/src/store/index.ts
  client/src/store/rootReducer.ts
  client/src/store/rootSaga.ts
  client/src/validators/index.ts
  client/src/validators/validateQuestions.ts
  client/src/validators/validateResults.ts
  client/src/validators/validateStatistics.ts
  client/tsconfig.json
  client/webpack.config.js
  client/webpack.dev.config.js
  server/public/bundle.js.gz
  server/src/index.js
  server/src/routes/ROUTES.md
Labels: feature, frontend

#67 Add information about routes and problem generation
  README.md
  docs/images/Bitwise.png
  docs/images/HalfMagicSquare.png
  docs/images/MainPage.png
  docs/images/MissingElement.png
  docs/images/Sudoku.png
  docs/images/Sum.png
  docs/images/TwoFiguresEasy.png
  docs/images/TwoFiguresMedium.png
  docs/images/favicon.png
  docs/src/Client/Main.md
  docs/src/Documentation/Documentation.md
  docs/src/Server/Problems.md
  docs/src/Server/Routing.md
  docs/src/Server/problems/Bitwise.md
  docs/src/Server/problems/HalfMagicSquare.md
  docs/src/Server/problems/MissingElement.md
  docs/src/Server/problems/Sudoku.md
  docs/src/Server/problems/Sum.md
  docs/src/Server/problems/TwoFiguresEasy.md
  docs/src/Server/problems/TwoFiguresMedium.md
  docs/src/Server/routes/AnswersRoute.md
  docs/src/Server/routes/FeedbackRoute.md
  docs/src/Server/routes/QuestionsRoute.md
  docs/src/Server/routes/ReportRoute.md
  docs/src/Server/routes/StatisticsRoute.md
  docs/styleguide.config.js
  server/src/routes/ROUTES.md
Labels: documentation
